version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./data:/app/data
    environment:
      - MAX_WORKERS=4
      - UPLOAD_FILE_SIZE_LIMIT=10485760  # 10MB
    restart: unless-stopped